print("this is just a test to know how the thing works")
print("Again!!!!!!")
print("this is just a test to know how the thing works")
print("Again!!!!!!")
print("this is just a test to know how the thing works")
print("Again!!!!!!")
print("this is just a test to know how the thing works")
print("Again!!!!!!")
print("this is just a test to know how the thing works")
print("Again!!!!!!")