from client0 import Client

SERVER_IP = "localhost"
SERVER_PORT = 8080
BASES = "ACCTCCTCTCCAGCAATGCCAACCCCAGTCCAGGCCCCCATCCGCCCAGGATCTCGATCA"
GENES = ["ADA", "FRAT1", "FXN", "RNU6_269P", "U5"]

# Exercise 1